spring.application.name=Profile Service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5431/profiles
##spring.datasource.username=${USERNAME}
##spring.datasource.password=${PASSWORD}
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.error.include-message=always
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hightlight_sql=true
#spring.cloud.config.enabled=false
token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=profile_microservice
spring.kafka.consumer.auto-offset-reset=earliest

